# basic
cinst sysinternals
cinst microsoft-windows-terminal
cinst cascadia-code-nerd-font
cinst terminal-icons.powershell
cinst 7zip
cinst git
cinst mousewithoutborders
cinst winscp
cinst ditto
cinst everything
