#!/bin/sh

# TODO: wired
# iwconfig eth2 2>&1 | grep -q no\ wireless\ extensions\. && {
#  echo wired
#  exit 0
# }

wifiWidget='<fn=2>\xf6ac</fn>' # no wifi
essid=`nmcli -t -f active,ssid dev wifi | grep '^yes' | awk -F ':' '{print $2}'`

[ -z "$essid" ] && {
  echo $wifiWidget
  exit 0
}

strength=`nmcli -t -f active,signal dev wifi | grep '^yes' | awk -F ':' '{print $2}'`

[ "$strength" -gt 80 ] && {
  echo 'strong'
}

# bars=`expr $stngth / 10`

# case $bars in
#   0)  bar='[----------]' ;;
#   1)  bar='[/---------]' ;;
#   2)  bar='[//--------]' ;;
#   3)  bar='[///-------]' ;;
#   4)  bar='[////------]' ;;
#   5)  bar='[/////-----]' ;;
#   6)  bar='[//////----]' ;;
#   7)  bar='[///////---]' ;;
#   8)  bar='[////////--]' ;;
#   9)  bar='[/////////-]' ;;
#   10) bar='[//////////]' ;;
#   *)  bar='[----!!----]' ;;
# esac

echo $essid $strength

# nmcli -t -f active,ssid,signal dev wifi | rg ^yes

