#!/usr/bin/env bash

echo -n 'work' > ~/.context

# navigating to work dir
cd $(
    fd \
        --type directory \
        --unrestricted \
        --max-depth 5 \
        --exclude .cache --exclude .asdf --exclude .local --exclude .cargo \
        --prune ^.git$ ~ | 
    awk 'NF{NF-=2} { print "[" $NF "] " $0 }' FS='/' OFS='/' |
    fzf |
    awk '{ print $2 }'
)

# adding work folder on context
pwd | xargs echo -n "$1" >> ~/.context

nvim .

